# Generated by Django 4.2 on 2024-08-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.IntegerField(blank=True, null=True, verbose_name='CPF')),
                ('cnpj', models.IntegerField(blank=True, null=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Reclamadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Reclamada',
                'verbose_name_plural': 'Reclamadas',
            },
        ),
        migrations.CreateModel(
            name='Reclamantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Reclamante',
                'verbose_name_plural': 'Reclamantes',
            },
        ),
        migrations.CreateModel(
            name='TipoServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='processos.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(max_length=26, verbose_name='N.Processo')),
                ('dt_ajuizamento', models.DateField(verbose_name='D.Ajuizamento')),
                ('formato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato')),
                ('dt_ult_atualizacao', models.DateField(blank=True, null=True, verbose_name='Ultima Atualização')),
                ('dt_ult_verificacao', models.DateField(blank=True, null=True, verbose_name='Ultima Verificação')),
                ('reclamada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.reclamadas', verbose_name='Reclamada')),
                ('reclamante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.reclamantes', verbose_name='Reclamante')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
